homeassistant:
  auth_providers:
    - type: homeassistant  
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/24
  name: Hidden Ridge
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 360
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize


config:
discovery:
#  ignore: harmony
frontend: !include ./configuration/frontend.yaml
history: !include ./configuration/history.yaml
logbook: !include ./configuration/logbook.yaml
logger: !include ./configuration/logger.yaml
lovelace:
  mode: yaml
map:
recorder: !include ./configuration/recorder.yaml
sun:
updater:

asuswrt: !include ./configuration/asuswrt.yaml
automation: !include_dir_merge_list automation
binary_sensor: !include ./configuration/binary_sensor.yaml
camera: !include ./configuration/camera.yaml
#cast: !include ./configuration/cast.yaml
climate: !include ./configuration/climate.yaml
cover: !include ./configuration/cover.yaml
device_tracker: !include ./configuration/device_tracker.yaml
google: !include ./configuration/calendar.yaml
#google_assistant: !include ./configuration/google_assistant.yaml
group: !include ./configuration/group.yaml
http: !include ./configuration/http.yaml
hue: !include ./configuration/hue.yaml
ifttt: !include ./configuration/ifttt.yaml
input_boolean: !include ./configuration/input_boolean.yaml
input_number: !include ./configuration/input_number.yaml
input_select: !include ./configuration/input_select.yaml
light: !include ./configuration/light.yaml
lock: !include ./configuration/lock.yaml
media_player: !include ./configuration/media_player.yaml
mqtt: !include ./configuration/mqtt.yaml
nest: !include ./configuration/nest.yaml
notify: !include ./configuration/notify.yaml
octoprint: !include ./configuration/octoprint.yaml
person:
pi-hole: !include ./configuration/pi-hole.yaml
plex: !include ./configuration/plex.yaml
#remote: !include ./configuration/remote.yaml
script: !include_dir_merge_named script
sensor: !include ./configuration/sensor.yaml
shell_command: !include ./configuration/shell_command.yaml
system_health:
switch: !include ./configuration/switch.yaml
tuya: !include ./configuration/tuya.yaml
tts: !include ./configuration/tts.yaml
weather: !include ./configuration/weather.yaml  
zone: !include ./configuration/zone.yaml
