homeassistant:
  name: Hidden Ridge
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 360
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

logger:
  default: info
  logs:
    homeassistant.components.media_player: error
config:
discovery:
frontend: 
  themes: !include ./themes/themes.yaml
map:
history:
  exclude:
    domains:
      - automation
    entities:
      - sensor.time_2
      - binary_sensor.downstairs_thermostat_has_leaf
      - binary_sensor.downstairs_thermostat_is_locked
      - binary_sensor.downstairs_thermostat_is_using_emergency_heat
      - binary_sensor.rain
      - binary_sensor.ring_doorbell
      - binary_sensor.upstairs_thermostat_has_leaf
      - binary_sensor.upstairs_thermostat_is_locked
      - binary_sensor.upstairs_thermostat_is_using_emergency_heat
      - device_tracker.04a316528e3b
      - device_tracker.chromecast
      - device_tracker.chromecast_audio
      - device_tracker.comcastmodem
      - device_tracker.crystals_phone_bt
      - device_tracker.crystals_phone_wifi
      - device_tracker.directv_genie
      - device_tracker.google_home
      - device_tracker.harmonyhub
      - device_tracker.huebridge
      - device_tracker.kevobridge
      - device_tracker.macmini
      - device_tracker.myq
      - device_tracker.rasplex
      - device_tracker.ring
      - device_tracker.smartthingshub
      - device_tracker.tristans_phone_bt
      - device_tracker.tristans_phone_wifi
      - device_tracker.viziocrave360
      - group.alarm_zones
      - group.all_automations
      - group.all_covers
      - group.all_devices
      - group.all_lights
      - group.all_remotes
      - group.all_scripts
      - group.all_switches
      - group.christmas
      - group.chromecasts
      - group.default_view
      - group.devices
      - group.dining_room
      - group.door_locks
      - group.exterior
      - group.foyer
      - group.garage
      - group.inputs
      - group.kitchen
      - group.lights
      - group.living_room
      - group.living_room_home
      - group.living_room_lights
      - group.master_bedroom
      - group.media
      - group.override
      - group.routines
      - group.settings
      - group.shell_commands
      - group.simulate_presence
      - group.stairway
      - group.system_monitor
      - group.tristal
      - group.upstairs
      - group.vacation_mode
      - group.weather
      - group.windows
      - input_boolean.back_door_open
      - input_boolean.disable_alarm
      - input_boolean.fan_check
      - input_boolean.front_door_open
      - input_boolean.garage_hot_start
      - input_boolean.wan_down
      - input_select.harmony
      - light.communal
      - light.dining_room_left
      - light.dining_room_right
      - light.foyer_left
      - light.foyer_right
      - light.front_door_2
      - light.kitchen
      - light.living_room
      - light.master_bedroom
      - light.saved_brightness
      - remote.living_room
      - remote.livingroom
      - script.abc
      - script.away_mode__day
      - script.away_mode__night
      - script.away_mode__rain
      - script.back_door_open
      - script.bedtime_lights
      - script.both_doors_open
      - script.cartoonnetwork
      - script.cbs
      - script.christmas
      - script.close_the_garage
      - script.comedycentral
      - script.door_status_check
      - script.espn
      - script.fan_off
      - script.fan_on
      - script.fox
      - script.foyer_lights_off
      - script.front_door_motion
      - script.front_door_open
      - script.fx
      - script.fxx
      - script.go_tigers_go
      - script.good_morning
      - script.goodbye
      - script.goodnight
      - script.goodnight_timer_off
      - script.lock_doors
      - script.mute
      - script.nbc
      - script.nest_hot_start
      - script.nightlight
      - script.open_the_garage
      - script.pause
      - script.pause_directv
      - script.pause_other
      - script.pause_plex
      - script.revert
      - script.stpaddysday
      - script.timer_off
      - script.unlock_doors
      - script.unpause
      - script.unpause_other
      - script.update_hass
      - script.volume_down
      - script.volume_up
      - script.whitenoise
      - script.who_dat
      - sensor.brightness_lr
      - sensor.brightness_pantry
      - sensor.color_temp_br
      - sensor.color_temp_cl
      - sensor.color_temp_lr
      - sensor.dark_sky_icon
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_summary
      - sensor.doorbell_battery
      - sensor.pws_alerts
      - sensor.pws_precip_1d
      - sensor.pws_weather_1d
      - sensor.time
      - sensor.whitenoise
      - sun.sun
      - switch.routines
      - switch.vacation_mode
      - zone.home
logbook:
  exclude:
    entities:
      - sensor.pws_weather_1d
      - sensor.load_5m
      - sensor.time_2
      - sensor.cpu
      - sensor.disk
      - sensor.ram
      - sensor.air_quality
      - sensor.rasplex
recorder:
#  db_url: postgres://@/hass
  purge_interval: 1
  purge_keep_days: 7
sun:
updater:

automation: !include_dir_merge_list automation
binary_sensor: !include ./configuration/binary_sensor.yaml
google: !include ./configuration/calendar.yaml
climate: !include ./configuration/climate.yaml
cover: !include ./configuration/cover.yaml
device_tracker: !include ./configuration/device_tracker.yaml
hue: !include ./configuration/hue.yaml
google_assistant: !include ./configuration/google_assistant.yaml
group: !include ./configuration/group.yaml
http: !include ./configuration/http.yaml
ifttt: !include ./configuration/ifttt.yaml
input_boolean: !include ./configuration/input_boolean.yaml
input_select: !include ./configuration/input_select.yaml
input_number: !include ./configuration/input_number.yaml
light: !include ./configuration/light.yaml
lock: !include ./configuration/lock.yaml
media_player: !include ./configuration/media_player.yaml
mqtt: !include ./configuration/mqtt.yaml
nest: !include ./configuration/nest.yaml
notify: !include ./configuration/notify.yaml
remote: !include ./configuration/remote.yaml
script: !include_dir_merge_named script
sensor: !include ./configuration/sensor.yaml
shell_command: !include ./configuration/shell_command.yaml
switch: !include ./configuration/switch.yaml
tts: !include ./configuration/tts.yaml
